### ISSUE TITLE
几个需要讨论的问题

### ISSUE THREAD

**Issue by captainblue2013** [captainblue2013/lat-runner#2]
1.能不能限制使用同一端口, 比如 80,  (为了简化集成)

2.暂时未能解决域名问题
  2.1 二级域名泛解析可以实现, 但是估计我们拿不到 *.freeCodeCamp.com
  2.2 其他域名, 面临备案的问题, 估计时间不足

3.依赖的问题
  3.1 mysql, redis 之类的依赖怎么解决? 是参赛组自行解决还是我们提供?
  3.2 我们提供的话, 就要出个教程如何使用, 这块我可以抽时间讲解.

**Comment by Akagilnc** [comment]
redis集中提供倒是没所谓。数据库的话很难保证所有人都想用mysql。
这一块我会倾向于我们提供。但是不强制要求使用

**Comment by too** [comment]
只用一个二级域名，然后对应不同路径怎样？  比如 fcc.com/aproject, fcc.com/bproject

**Comment by captainblue2013** [comment]
@Dean266 我感觉还是不要提供任何基础存储方案, 不然对我们风险很大, 很不可控

**Comment by captainblue2013** [comment]
域名方面就用
http://chengdu.freecodecamp.com/{project} 这个方案吧,
除非有更好的方式,否则就按这个方式推进

**Comment by captainblue2013** [comment]
问题回顾一下:
1.域名问题, 使用 chengdu.freecodecamp.cn/{project}
2.存储方案决定不提供了
3.未定的内容:
3.1 教程/文档/说明 (随便叫什么), 再安排时间讨论
